### ISSUE TITLE
SVI at ZCTA level

### ISSUE THREAD

**Issue by alinasmahl1** [heli-xu/svi-calculation#3]
years: varying
geo-unit: CTA
What areas are you interested in: Several states- please see below

state,year,n
AZ,2015,8
AZ,2016,2
AZ,2017,2
AZ,2018,2
AZ,2019,3
FL,2014,4
FL,2015,8
GA,2015,8
GA,2016,2
GA,2017,2
GA,2018,2
GA,2019,3
KY,2012,4
KY,2013,4
KY,2014,4
KY,2015,8
MA,2013,4
MA,2014,4
MA,2015,8
MA,2016,2
MA,2017,2
NJ,2012,4
NJ,2013,4
NJ,2014,4
NJ,2015,8
NJ,2016,2
NJ,2017,2
NY,2017,4
NY,2018,4

**Comment by heli-xu** [comment]
Hi Alina, thanks for your interest and patience. I've been working on the SVI package (findSVI) before processing the requests for better reproducibility, and the initial version of [findSVI](https://heli-xu.github.io/findSVI/index.html) is now available for install from github. I'm attaching a table with theme-specific and overall SVIs for all the ZCTAs your requested, and the process to produce the result is documented [here](https://heli-xu.github.io/svi-calculation/posts/Run_multiple_requests_with_findSVI/Run_multiple_requests_with_findSVI.html). Please let me know if you have any questions, and I'd appreciate any feedbacks/suggestions. 
[result_for_alina.zip](https://github.com/heli-xu/svi-calculation/files/11606425/result_for_alina.zip)

**Comment by heli-xu** [comment]
Hi Alina, I'm going to close this issue here for now. If you have further questions/feedback, please feel free to create another issue on the [findSVI package repo](https://github.com/heli-xu/findSVI). Thanks!
